language: node_js

node_js:
  - "8"
  - "10"
  - "11"

before_script:
  - npm install big-time --save-dev
  - npm install istanbul --save-dev

install:
  - npm install -g codecov --save-dev

script:
  - npm test
  - istanbul cover ./node_modules/lab/bin/lab --report lcovonly  -- -l
  - codecov
